language: node_js
node_js:
- 7.9.0
script:
- pwd
- ls
- cd frontend
- npm install
- npm run build
- git checkout -b master
before_install:
- git config --global user.name "Travis CI"
- git config --global user.email "thomas@novamedia.nyc"
before_deploy:
- git status
- chmod +x deploy.sh
- ./deploy.sh
deploy:
  provider: heroku
  app: nova-xr-media
  api_key:
    secure: PDd+4+fWHFncuip0nyvaa1Q5ZAs1qhwuh0tSNykyjbhKs02O4icYBV8xBfI843Vzvv9lfAjNGVPDxhjHygjh2MgfjWdwOZte+P8f0lKef+5KG5DXqN2Gt4wdPFZRsieSUla+AO1eSJZJSCp1kFkaTqhbfNuFyI/bWCTL1y/s7NZbfAKdvTyzG7eSMQ30bIZbfuR3Dnxm3ycFUwVUl007qcidQiOb9QST47/8fbxCXcQPxxfSRSA5ToDmZUsr4JTTPaacnOvURjqlmTB5ZCyKXoyqQFE0hGiUIGEylWDFbAy0Xkd5TX0lfZvgcFZOGlvSQJWlLWznmC8ftx0mIDLPB5ZPJaGEn4HCAbOtzivjyZ6tWjNIAJ8p83ffBOcxhXv0kESOI8gJpNXgnE8c5PjdfQ0cHXcrBQDA72DWbaKspgEjLzVP3aJtpJY14v5WdvxoPdVxRd3QncaWnKwWXFWPX8VGYRolzDxLCuvX4xJrOEJMI+Vor8IUn7y5hOw1iwqlqM2a0vyt6Wv27bMaUDRcaCYaf0FNex4yfL8U/hOvxSsjfscZZK/bDYfUvDV9pnMepkM4U1edZq95HHyR4tIY6ve+PFo/RGVl6yRL9+1wq+PsEnjq5hB8EEUn2LHCbQ2yOEmxYqhUpr8YEGlijWqAVaVr8Gfvh4o/x6RG4LsbGwg=
  on:
    all_branches: true
